---
- name: install playbook
  hosts: all
  tasks:  
    - name: installing tree
      apt:
        name: tree
        state: latest

    - name: ensuring ssh running or not
      service: 
        name: sshd
        state: started
    
    - name: running apt update
      apt:
        update_cache: true

    - name: file is used to create a file
      file:
        path: /root/test1
        state: touch
        mode: 0777      
